Syntax ::=
    FastBCPCommand FastBCPOptions

FastBCPCommand ::=
    ( "'.\FastBCP.exe'" | "'./fastbcp'" )

FastBCPOptions ::=
    "--connectiontype" ConnectionType
    ConnectionParameters
    SourceInfos
    (OutputInfoCSV (|FormatCSVOptions) | OutputInfoJSON (|FormatJSONOptions) | OutputInfoXLSX (|FormatXLSXOptions) | OutputInfoParquet | OutputInfoBinary)
    (|AdvancedParameters)
    (|LogParameters)    
    (|LicenceParameters)

ConnectionType ::=
    ( "clickhouse"
    | "duckdb"
    | "hana"
    | "mssql"
    | "mysql"
    | "nzsql"
    | "odbc"
    | "oledb"
    | "oraodp"
    | "pgcopy"
    | "pgsql"
    | "teradata"
    )

ConnectionParameters ::=
    (
    ( 
      "--server"
      ("Host" | "Host:Port" | "Host\InstanceName" | "Host:Port/TNSService" ) 
      (|"--provider" OLEDBProvider)
      |("--dsn" DSNName)
        )
      ( "--trusted"  | ( "--user" "Username" "--password" "Password" ))
      "--database" "DatabaseName"
    )
    
  | ( "--connectionstring" "ConnectString" )


SourceInfos ::=
    (( "--sourceschema" SchemaName "--sourcetable" TableName) | ("--query" Query | ( "--query" Query "--sourceschema" SchemaName "--sourcetable" TableName)) | ("--fileinput" InputFilePath | ("--fileinput" InputFilePath "--sourceschema" SchemaName "--sourcetable" TableName)))


OutputInfoCSV ::=
     "--fileoutput" (FileName.csv|FileName.tsv) 
     "--directory" OutputDirectory
     (|"--timestamped")
     (|"--encoding" Encoding)

FormatCSVOptions ::=
     (|"--delimiter" Delimiter)
     (|"--dateformat" DateFormat)
     (|"--decimalseparator" DecimalSeprator)
     (|"--quotes" ( "true" | "false" ))
     (|"--noheader")
     (|("--boolformat" ("automatic"|"1/0"|"true/false"|"t/f")))

OutputInfoJSON ::=
     "--fileoutput" (FileName.json) 
     "--directory" OutputDirectory
     (|"--timestamped")
     (|"--encoding" Encoding)

FormatJSONOptions ::=
     (|"--dateformat" DateFormat)
     (|"--decimalseparator" DecimalSeprator)


OutputInfoParquet ::=
     "--fileoutput" FileName.parquet 
     "--directory" OutputDirectory

OutputInfoXLSX ::=
     "--fileoutput" (FileName.xlsx) 
     "--directory" OutputDirectory
     (|"--timestamped")

FormatXLSXOptions ::=
     (|"--dateformat" DateFormat)
     (|"--decimalseparator" DecimalSeprator)
     
OutputInfoBinary ::=
     "--fileoutput" FileName.binary 
     "--directory" OutputDirectory

AdvancedParameters ::=
     "--method" ( "None"| ((("Random" | "DataDriven" | "RangeId" | "Ntile" ) "--distributekeycolumn" KeyColumn) | "Ctid" | "Rowid"  ) "--paralleldegree" Degree "--merge" ( "true" | "false" )) 

LogParameters ::=
    (|"--runid" RunId)
    (|"--settingsfile" SettingsFile)

LicenceParameters ::=
    (|"--licence" (Licencefile|Licenceurl))

